package ascensor;

/**
 *
 * @author LPS
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form frameVisual
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        selectPisos = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        selectSotanos = new javax.swing.JComboBox<>();
        botonSubir = new javax.swing.JButton();
        botonBajar = new javax.swing.JButton();
        labelTotalPisos = new javax.swing.JLabel();
        labelPosicionAscensor = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        selectPisos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "60", "61", "62", "63", "64", "65", "66", "67", "68", "69", "70", "71", "72", "73", "74", "75", "76", "77", "78", "79", "80", "81", "82", "83", "84", "85", "86", "87", "88", "89", "90", "91", "92", "93", "94", "95", "96", "97", "98", "99", "100" }));
        selectPisos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectPisosActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Panel de control del ascensor");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Seleccione la cantidad de pisos del edificio");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Seleccione la cantidad de sotanos del edificio");

        selectSotanos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        selectSotanos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectSotanosActionPerformed(evt);
            }
        });

        botonSubir.setText("Subir");
        botonSubir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSubirActionPerformed(evt);
            }
        });

        botonBajar.setText("Bajar");
        botonBajar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBajarActionPerformed(evt);
            }
        });

        labelTotalPisos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTotalPisos.setText("Con los valores actuales el ascensor atiende 1 piso");
        labelTotalPisos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        labelPosicionAscensor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelPosicionAscensor.setText("El ascensor ahora esta en el piso No. 1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labelTotalPisos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(labelPosicionAscensor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(79, 79, 79)
                                .addComponent(botonSubir)
                                .addGap(69, 69, 69)
                                .addComponent(botonBajar))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(166, 166, 166)
                                .addComponent(selectSotanos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(162, 162, 162)
                                .addComponent(selectPisos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 128, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(selectPisos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(selectSotanos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelTotalPisos)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonSubir)
                    .addComponent(botonBajar))
                .addGap(18, 18, 18)
                .addComponent(labelPosicionAscensor)
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    // cuando se selecciona la cantidad de sotanos
    private void selectSotanosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectSotanosActionPerformed
        String cantSotanos = (String) selectSotanos.getSelectedItem();
        int sotanos = Integer.parseInt(cantSotanos);
        metodos.setSotanos(sotanos);
        
        int sotanosAtendidos = metodos.getAtendidos();
        String atendidos = Integer.toString(sotanosAtendidos);
        
        labelTotalPisos.setText("La cantidad de pisos que atiende el ascensor es de: " + atendidos);
    }//GEN-LAST:event_selectSotanosActionPerformed
    
    //cuando se selecciona la cantidad de pisos
    private void selectPisosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectPisosActionPerformed
       String cantPisos = (String) selectPisos.getSelectedItem();
        
       int pisos = Integer.parseInt(cantPisos);  
       metodos.setPisos(pisos);
       
       int pisosAtendidos = metodos.getAtendidos();
       String atendidos = Integer.toString(pisosAtendidos);
       
       labelTotalPisos.setText("La cantidad de pisos que atiende el ascensor es de: " + atendidos);
    }//GEN-LAST:event_selectPisosActionPerformed
    
    //cuando se presiona el boton de subir
    private void botonSubirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSubirActionPerformed
        metodos.setPisoSubiendo();
        
        int pisoActual = metodos.getPisoActual();
        String texto = "";
        
        if(pisoActual < 0) {
            texto = "El ascensor esta en el sotano # ";
        }
        else {
            texto = "El ascensor esta en el piso # ";
        }
        
        String pActual = Integer.toString(pisoActual);
        
        labelPosicionAscensor.setText(texto + pActual);        
    }//GEN-LAST:event_botonSubirActionPerformed
    
    //cuando se presiona el boton bajar
    private void botonBajarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBajarActionPerformed
        metodos.setPisoBajando();
        
        int pisoActual = metodos.getPisoActual();
        String texto = "";
        
        if(pisoActual < 0) {
            texto = "El ascensor esta en el sotano # ";
        }
        else {
            texto = "El ascensor esta en el piso # ";
        }
        
        String pActual = Integer.toString(pisoActual);
        
        labelPosicionAscensor.setText(texto + pActual);
    }//GEN-LAST:event_botonBajarActionPerformed

    /**
     * @param args the command line arguments
     */
    static Ascensor1 metodos;
    public static void main(String args[]) {
       
       int pisos = 1; // cantidad de pisos del edificio
       int down = 0;  // cantidad de sotanos del edificio
       int actual = 1; // piso inicial en el que esta la persona
       int total = 1;  // para almacenar la cantidad de pisos que atiende el ascensor
       
       metodos = new Ascensor1(pisos, down, actual, total);

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonBajar;
    private javax.swing.JButton botonSubir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel labelPosicionAscensor;
    private javax.swing.JLabel labelTotalPisos;
    private javax.swing.JComboBox<String> selectPisos;
    private javax.swing.JComboBox<String> selectSotanos;
    // End of variables declaration//GEN-END:variables
}
